import { BaseAgent } from "./base.agent.js";
import { getMedPsy1B } from "../models/pool.js";
import type { AgentName, AgentProgressEvent } from "@diamesh/shared";
import type { DifferentialResult } from "./differential.agent.js";

export interface EducationResult {
  content: string;
  disclaimer: string;
}

export class EducationAgent extends BaseAgent {
  readonly name: AgentName = "education";

  async generate(
    caseId: string,
    patientName: string,
    differentialResult: DifferentialResult,
    onEvent?: (e: AgentProgressEvent) => void
  ): Promise<EducationResult> {
    const modelId = await getMedPsy1B();

    const topCondition = differentialResult.differentials[0];
    const actionsList = differentialResult.recommendedActions
      .map((a, i) => `${i + 1}. ${a}`)
      .join("\n");

    const result = await this.run({
      caseId,
      modelId,
      modelName: "MedPsy-1.7B",
      tools: [],
      captureThinking: false,
      onEvent,
      systemPrompt: `You are a patient educator at an eye clinic. Write clear, compassionate, plain-language content for patients.
Use simple language (no medical jargon without explanation).
Be reassuring but honest. Do not alarm the patient unnecessarily.
Never provide specific treatment recommendations — only explain what to expect and why follow-up matters.`,

      userPrompt: `Create a patient education summary for ${patientName}.

Primary finding of concern: ${topCondition?.condition ?? "Ophthalmic condition requiring follow-up"}
${topCondition?.rationale ? `Brief explanation: ${topCondition.rationale}` : ""}

Recommended next steps from your care team:
${actionsList}

Write a patient-friendly explanation (3-4 paragraphs) covering:
1. What was found and why it matters (in plain language)
2. What the recommended next steps mean for the patient
3. What signs/symptoms should prompt immediate re-attendance
4. Encouragement and emphasis on the importance of follow-up`,
    });

    return {
      content: result.text,
      disclaimer:
        "IMPORTANT: This information is for educational purposes only and is generated by an AI assistant. It does not replace advice from your qualified healthcare provider. Always follow the guidance of your clinician. If you experience sudden vision loss, eye pain, or flashes of light, seek immediate medical attention.",
    };
  }
}
