import { BaseAgent } from "./base.agent.js";
import { getReasoningSmall } from "../models/pool.js";
import { MODEL_DISPLAY } from "../models/constants.js";
import type { AgentName, AgentProgressEvent } from "@diamesh/shared";
import type { DifferentialResult } from "./differential.agent.js";

export interface EducationResult {
  content: string;
  disclaimer: string;
}

export class EducationAgent extends BaseAgent {
  readonly name: AgentName = "education";

  async generate(
    caseId: string,
    patientName: string,
    differentialResult: DifferentialResult,
    onEvent?: ((e: AgentProgressEvent) => void) | undefined
  ): Promise<EducationResult> {
    const modelId = await getReasoningSmall();

    const topCondition = differentialResult.differentials[0];
    const actionsList = differentialResult.recommendedActions
      .map((a, i) => `${i + 1}. ${a}`)
      .join("\n");

    const result = await this.run({
      caseId,
      modelId,
      modelName: MODEL_DISPLAY.REASONING_SMALL,
      tools: [],
      onEvent,
      systemPrompt: `You are assisting an eye care clinician by preparing a patient-communication briefing.

This is guidance FOR THE CLINICIAN on how to talk to the patient — it is NOT a
message to be read by the patient directly. Write in the second person
addressed to the clinician (e.g. "Explain to the patient that...",
"Reassure them that...", "Advise the patient to..."). Never address the
patient directly as "you".

Use clear, jargon-light phrasing the clinician can adapt in conversation.
Be reassuring but honest, and do not suggest alarming the patient unnecessarily.
Do not invent treatment recommendations beyond the next steps provided.`,

      userPrompt: `Prepare a patient-communication briefing for the clinician regarding ${patientName}.

Primary finding of concern: ${topCondition?.condition ?? "Ophthalmic condition requiring follow-up"}
${topCondition?.rationale ? `Clinical rationale: ${topCondition.rationale}` : ""}

Recommended next steps:
${actionsList}

Write guidance for the clinician (3-4 short sections) covering:
1. How to explain this finding to the patient in plain language
2. How to frame the recommended next steps so the patient understands their importance
3. Warning signs/symptoms to tell the patient to watch for, and to seek immediate care if they occur
4. Reassurance points to include so the patient doesn't feel unduly alarmed`,
    });

    return {
      content: result.text,
      disclaimer:
        "IMPORTANT: This information is for educational purposes only and is generated by an AI assistant. It does not replace advice from your qualified healthcare provider. Always follow the guidance of your clinician. If you experience sudden vision loss, eye pain, or flashes of light, seek immediate medical attention.",
    };
  }
}
